apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: flask-aws-monitor-environments
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/CSboylol/gitops.git
        revision: main
        directories:
          - path: deployments/*
  template:
    metadata:
      name: 'flask-aws-monitor-{{path.basename}}'
    spec:
      project: gitops-project
      source:
        repoURL: https://github.com/CSboylol/gitops.git
        targetRevision: main
        path: '{{path}}'
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: 'flask-aws-monitor-{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
