apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitops-project
  namespace: argocd
spec:
  description: Allow access to CSboylol GitOps repositories
  sourceRepos:
    - https://github.com/CSboylol/gitops.git
    - https://github.com/CSboylol/flask-aws-monitor-helm.git
    - https://stefanprodan.github.io/podinfo
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  sourceNamespaces:
    - '*'
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
